[env:smoochiee-board]
board = smoochiee-board
build_src_filter = ${env.build_src_filter} +<../boards/smoochiee-board>

; Board & Memory
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = custom_16Mb.csv
board_build.filesystem = littlefs

; Build Flags
build_flags =
    ${env.build_flags}
    -Iboards/smoochiee-board
    -Os
    -DCORE_DEBUG_LEVEL=1
    
    ; USB-CDC & PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    
    ; Dual SPI & Device Config
    -DSEPARATE_SPI_BUSES=1
    -DUSE_HSPI_PORT=1
    -DDEVICE_NAME='"Smoochiee Board"'
    -DBUZZ_PIN=44
    -DMIC_INMP441
    -DBRUCE_PIN_ARRAYS
    
    ; Pin Arrays (JSON format)
    -DIR_TX_PINS='{{"M5 IR Mod", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"GPIO 5", 5}, {"GPIO 2", 2}}'
    -DIR_RX_PINS='{{"M5 IR Mod", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"GPIO 4", 4}, {"GPIO 2", 2}}'
    -DRF_TX_PINS='{{"M5 RF433T", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"GPIO 1", 1}, {"GPIO 2", 2}}'
    -DRF_RX_PINS='{{"M5 RF433R", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"GPIO 1", 1}, {"GPIO 2", 2}}'

lib_deps =
    ${env.lib_deps}
    lewisxhe/XPowersLib @0.3.0
